### ISSUE TITLE
Time of heft simulation is less than lookahead

### ISSUE THREAD

**Issue by Ksenia-C** [osukhoroslov/dslab#166]
Алгоритмы оптимизируют время завершения последней задачи, но суммарное время может оказаться больше из-за передачи последних данных.

В чем заключается странность - в реализации lookahead при переборе ресурса, куда поставить задачу, heft запускается до самого конца. Значит lookahead всегда при переборе учтет решение с heft, возможно улучшит, а значит время завершения должно быть всегда меньше времени для heft. Под временем я подразумеваю ```sim.time()```.

На текоторых тестах heft опережает lookahead.

Входные файлы для графа:
[finished_not_optimized_dag.txt](https://github.com/osukhoroslov/dslab/files/10174085/finished_not_optimized_dag.txt)
Для ресурсов
[finished_not_optimized_resources.txt](https://github.com/osukhoroslov/dslab/files/10174088/finished_not_optimized_resources.txt)

Traces:

[finished_not_optimized_heft.log](https://github.com/osukhoroslov/dslab/files/10174095/finished_not_optimized_heft.log)
[finished_not_optimized_lookahead.log](https://github.com/osukhoroslov/dslab/files/10174096/finished_not_optimized_lookahead.log)

Если посмотреть, то последнее событие в heft заканчивается в _945244_, lookahead в _1424448_.
При этом сами задачи не противоречат рассуждениям - в heft последняя заканчивается в _744998_, lookahead в _485539_

**Comment by maksim1744** [comment]
Какая модель сети использовалась в этом примере?

**Comment by Ksenia-C** [comment]
@maksim1744 

`ConstantBandwidthNetwork::new(1.0, 0.0)`

`data_transfer_mode = DataTransferMode::Direct`

**Comment by osukhoroslov** [comment]
@Ksenia-C проверьте на ветке `main`, возможно проблема решена.

**Comment by Ksenia-C** [comment]
Для lookahead общее время уменьшилось до 1442417, последняя задача завершается в 544717. Heft без изменений, и поэтому `sim.time()` для него все меньше lookahead-а

[finished_not_optimized_lookahead.log](https://github.com/osukhoroslov/dslab/files/10309993/finished_not_optimized_lookahead.log)

**Comment by osukhoroslov** [comment]
У меня получились похожие результаты. Makespan: 14427.79 (Lookahead) vs 9455.53 (HEFT). 

Думаю дело в том, что [здесь](https://github.com/osukhoroslov/dslab/blob/6e4dd5dd04de69b267f185a55a8ae6e599594f5c/crates/dslab-dag/src/schedulers/lookahead.rs#L109) не учитывается время передачи результатов на мастер.

Поправил и выложил фикс [здесь](https://github.com/osukhoroslov/dslab/pull/179). С ним makespan у Lookahead стал 9455.21. 

@Ksenia-C проверьте.
